Repository Finschia/finschia, pull requests merged in 2023-10, with the labels that each got.

#281 docs: add guide for static build
  CHANGELOG.md
  docs/finschia-tutorials/installation.md
Labels: documentation

#290 ci: remove auto pr ci
  .github/workflows/autopr.yml
  CHANGELOG.md
Labels: ci

#291 ci: fix goreleaser error and replace release-build
  .github/workflows/release-build.yml
  .github/workflows/tag.yml
  .goreleaser.yml
  CHANGELOG.md
  Makefile
Labels: ci

#295 chore: set CODEOWNERS & backport action
  .github/CODEOWNERS
  .mergify.yml
  CHANGELOG.md
Labels: ci, automerge

#296 build(deps): bump actions/checkout from 3 to 4
  .github/workflows/check-generated.yml
  .github/workflows/ci-smart-contract.yml
  .github/workflows/docker.yml
  .github/workflows/format.yml
  .github/workflows/lint.yml
  .github/workflows/sims.yml
  .github/workflows/tests.yml
  CHANGELOG.md
Labels: dependencies, github_actions

#297 build: bump up finschia-sdk from v0.48.0 to v0.48.1
  CHANGELOG.md
  go.mod
  go.sum
Labels: backport/v2.0.x
