Repository Finschia/finschia, pull requests merged in 2023-07, with the labels that each got.

#238 Release finschia v1.1.0
  CHANGELOG.md
  RELEASE_CHANGELOG.md
  RELEASE_NOTE.md
  go.mod
  go.sum
Labels: release

#233 test: add smart contract CI test
  .github/workflows/ci-smart-contract.yml
  CHANGELOG.md
  ci_test/queue_ci.sh
Labels: ci

#241 build: update golang version to 1.20
  .github/workflows/check-generated.yml
  .github/workflows/lint.yml
  .github/workflows/sims.yml
  .github/workflows/tag.yml
  .github/workflows/tests.yml
  CHANGELOG.md
  CONTRIBUTING.md
  Dockerfile
  README.md
  docs/finschia-tutorials/installation.md
  go.mod
  networks/local/finschianode/Dockerfile
Labels: enhancement, ci
