Repository Finschia/finschia, pull requests merged in 2024-03, with the labels that each got.

#333 build(deps): Bump github.com/Finschia/ostracon from 1.1.2 to 1.1.3
  CHANGELOG.md
  go.mod
  go.sum
Labels: dependencies, backport/v2.0.x

#336 add RELEASE_NOTE generation script
  .github/workflows/tag.yml
  CHANGELOG.md
  RELEASE_CHANGELOG.md
  RELEASE_DESCR.md
  RELEASE_NOTE.md
  scripts/release-note.py
Labels: ci, backport/v2.0.x, backport/v3.0.x

#340 build: set Finschia/ostracon version
  CHANGELOG.md
  Makefile
Labels: backport/v2.0.x, backport/v3.0.x
