Repository Finschia/finschia, pull requests merged in 2024-05, with the labels that each got.

#354 build(deps): bump `finschia-sdk` v0.48.1 to v0.49.0-rc1
  .mergify.yml
  CHANGELOG.md
  app/app.go
  go.mod
  go.sum
Labels: enhancement, dependencies, backport/v4.0.x

#355 build(deps): bump `finschia-sdk` from v0.49.0-rc1 to v0.49.0-rc2
  CHANGELOG.md
  go.mod
  go.sum
Labels: backport/v4.0.x

#357 feat: upgrade to v4
  .github/workflows/check-generated.yml
  CHANGELOG.md
  ante/ante_test.go
  app/app.go
  app/encoding.go
  app/helpers/test_helpers.go
  cli_test/cli_test.go
  cli_test/multi_test.go
  cli_test/test_helpers.go
  cmd/fnsad/cmd/root.go
  cmd/fnsad/cmd/testnet_test.go
  cmd/fnsad/main.go
  go.mod
  interchaintest/go.mod
Labels: backport/v4.0.x

#359 build(deps): bump `finschia-sdk` from v0.49.0-rc2 to v0.49.0-rc3
  CHANGELOG.md
  app/app.go
  go.mod
  go.sum
Labels: enhancement, dependencies, backport/v4.0.x

#361 style: replace deprecated linters with new ones
  .golangci.yml
  CHANGELOG.md
  app/helpers/test_helpers.go
  cli_test/test_helpers.go
Labels: ci, backport/v4.0.x

#362 ci: add RELEASE_NOTE.md to .gitignore
  .gitignore
  CHANGELOG.md
Labels: ci, backport/v4.0.x

#366 bulid(deps): bump github.com/Finschia/finschia-sdk from v0.49.0-rc3 to v0.49.0-rc4
  CHANGELOG.md
  app/app.go
  go.mod
  go.sum
Labels: dependencies, backport/v4.0.x

#373 build: bump finschis-sdk from v0.49.0-rc4 to v0.49.0-rc5
  CHANGELOG.md
  go.mod
  go.sum
Labels: backport/v4.0.x
