Repository Finschia/finschia, pull requests merged in 2024-06, with the labels that each got.

#385 feat: Force user to follow the rule of release note generation
  CHANGELOG.md
  RELEASE_DESCR.md
  scripts/release-note.py
Labels: ci

#388 chore: Modify the way the binary version is set when compiling
  CHANGELOG.md
  Makefile
Labels: backport/v4.0.x

#395 feat: Apply finschia-sdk 0.49.1
  .github/workflows/check-generated.yml
  .github/workflows/ci-smart-contract.yml
  .github/workflows/docker.yml
  .github/workflows/e2e-ibc.yml
  .github/workflows/format.yml
  .github/workflows/lint.yml
  .github/workflows/sims.yml
  .github/workflows/tests.yml
  .golangci.yml
  .goreleaser.yml
  CHANGELOG.md
  CONTRIBUTING.md
  Dockerfile
  Makefile
  README.md
  ante/ante.go
  ante/ante_test.go
  app/app.go
  app/app_test.go
  app/export.go
  app/genesis_account_test.go
  app/wasm_filter.go
  app/wasm_filter_test.go
  cli_test/cli_test.go
  cli_test/test_helpers.go
  cmd/fnsad/cmd/genaccounts_test.go
  cmd/fnsad/cmd/root.go
  cmd/fnsad/cmd/root_test.go
  cmd/fnsad/cmd/testnet.go
  cmd/fnsad/cmd/testnet_test.go
  cmd/fnsad/main.go
  docs/finschia-tutorials/installation.md
  go.mod
  go.sum
  init_multi.sh
  interchaintest/go.mod
  networks/local/finschianode/Dockerfile
Labels: dependencies, github_actions, backport/v4.0.x
